## Example Config file
baseURL: "https://irak.li"
theme: "terminalcv"
title: "Irakli Chkuaseli"

params:
  # version: "2.0.0"
  description: "Irakli Chkuaseli"
  prompt: "irakli@here"
  promptColor: orange
  # promptSimbols: ":~$"
  # promptSimbolsColor: grey
  # startxLocation: https://example.com
  # useLess: true
  exitLocation: "about:blank"
  source: false
  greeting: |
    Type 'help' for a list of available commands

  whois:
    # settings:
    #   useLess: true
    details:
      name: "Irakli Chkuaseli"
      profession: "Game Developer"
      location: "Tbilisi, Georgia"
      # email: "foo@someemail.com"
      homelink: "https://irak.li"
      description: |

        I'm a game developer with a passion for creating interactive experiences.

  social:
    # settings:
    #   useLess: true
    #   hideName: true
    details:
      - name: "github"
        url: "https://github.com/irakli"
      - name: "linkedin"
        url: "https://linkedin.com/in/iraklichkuaseli"

  work:
    settings:
      useLess: true
    details:
      - jobTitle: Lead Unity Developer
        color: gold
        company: Golden Fox
        location: Tbilisi, Georgia
        date: November 2019 - Present
        description: |
          Led the design and development of a comprehensive 3D action game's code architecture.
          Managed a cross-functional team to deliver high-quality mobile and web games.
          Developed a robust character creation and customization system.

      - jobTitle: Senior Unity Developer
        color: red
        company: Qene Games
        location: Tbilisi, Georgia
        date: May 2023 - Present
        description: |
          Architected and implemented the core code structure for an upcoming game using Zenject.
          Developed multiple mini-games, enhancing user engagement and retention.
          Designed and integrated the game backend using Firebase.

      - jobTitle: Senior Unity Developer
        color: blue
        company: Toptal
        location: Remote
        date: February 2022 - Present
        description: |
          Developed a custom physics-based character controller and adapted an open-source ability system for a 2D side-scroller game.
          Created a realistic audio occlusion system and a modular user interface system.

      - jobTitle: Senior Unity Developer
        color: green
        company: Matchday
        location: Remote
        date: February 2023 - May 2023
        description: |
          Developed multiple NFT game prototypes and engineered reusable game services.

      - jobTitle: Senior Unity Developer
        color: yellow
        company: Sleepagotchi
        location: Remote
        date: September 2022 - November 2022
        description: |
          Designed and implemented a 3D real-time rendering solution in Unity, optimized for mobile devices.
          Developed a dynamic 3D room rendering system and implemented advanced volumetric lighting.

      - jobTitle: .NET Developer
        color: cyan
        company: Champions Academy
        location: Tbilisi, Georgia
        date: April 2020 - December 2021
        description: |
          Designed and developed an internal gym management system.
          Integrated existing gym hardware for seamless member access and created a comprehensive data analytics tool.

      - jobTitle: Unity Developer
        color: magenta
        company: Golden Fox
        location: Tbilisi, Georgia
        date: November 2018 - November 2019
        description: |
          Implemented core gameplay mechanics for a 2D fighting game.
          Developed leaderboards, statistics, and achievements.
          Designed and created the game's UI with animations, sounds, and haptic feedback.

  education:
    details:
      - courseName: Master of Science in Computer Science
        color: purple
        institution: Georgian Technical University
        location: Tbilisi, Georgia
        date: September 2021 - December 2023

      - courseName: Bachelor of Science in Computer Science
        color: yellow
        institution: Free University of Tbilisi
        location: Tbilisi, Georgia
        date: September 2014 - July 2018

  languages:
    # settings:
    #   useLess: true
    details:
      - name: English
        color: Blue
        percentage: 100
        description: Fluent

      - name: Georgian
        color: Red
        percentage: 100
        description: Native

      - name: Spanish
        color: yellow
        percentage: 70
        description: Intermediate

  projects:
  # settings:
  #   useLess: true
    details:
      - title: Guns and Fury
        color: red
        link: https://apps.apple.com/us/app/guns-fury/id1589304660
        description: |
          A fast-paced, action-packed mobile game with various weapons, challenging levels, endless zombie mode, and boss battles.

      - title: Beemi
        color: blue
        link: https://beemi.app/
        description: |
          A collection of interactive mini-games designed to enhance livestreaming experiences and actively engage audiences.

      - title: Sleepagotchi
        color: green
        link: https://apps.apple.com/app/sleepagotchi-sleep-tracker/id1619708062
        description: |
          An application to help achieve a consistent sleep schedule with rewards through collectible items and tokens.

      - title: Battle for Basiani
        color: yellow
        link: https://apps.apple.com/us/app/battle-for-basiani/id1495060685
        description: |
          An action-packed 2D beat 'em up mobile game with unique abilities and talents for each opponent.

  misc:
    # settings:
    #   useLess: true
